import { Student, GraduationChecklistItem, FormRecord } from '../types'

// NOTE: All dates in this file are fake placeholder dates for a Fall 2026
// cohort, used only to populate the UI. They must be replaced with real
// program dates once a backend and admin data entry exist.

function defaultGradChecklist(overrides: Partial<Record<string, boolean>> = {}): GraduationChecklistItem[] {
  const base: GraduationChecklistItem[] = [
    { id: 'idp-pd', label: 'IDP and PD completion form submitted', done: false },
    { id: 'courses', label: 'All six MM courses complete', done: false },
    { id: 'internship-credits', label: 'All internship credits complete (MM 807 + MM 808)', done: false },
    { id: 'bear-tracks', label: 'Applied for graduation in Bear Tracks', done: false },
    { id: 'final-grade', label: 'MM 808 final grade received', done: false },
    { id: 'completion-letter', label: 'Letter of Completion requested from FGSR', done: false },
  ]
  return base.map((item) => ({ ...item, done: overrides[item.id] ?? item.done }))
}

function defaultForms(overrides: Partial<Record<string, FormRecord['status']>> = {}): FormRecord[] {
  const base: { id: string; label: string; dueDate?: string }[] = [
    { id: 'idp-workbook', label: 'Individual Development Plan workbook', dueDate: '2026-12-15' },
    { id: 'ethics-records', label: 'Ethics training records (8 hrs)', dueDate: '2026-12-15' },
    { id: 'coop-permit', label: 'Co-op work permit application', dueDate: '2027-03-01' },
    { id: 'internship-approval', label: 'Internship approval form', dueDate: '2027-04-15' },
    { id: 'idp-pd-completion', label: 'IDP and PD completion form', dueDate: '2027-12-01' },
  ]
  return base.map((f) => ({ ...f, status: overrides[f.id] ?? 'not-started' }))
}

export const STUDENTS: Student[] = [
  {
    id: 'stu-001',
    name: 'Priya Nair',
    ccid: 'pnair',
    email: 'pnair@ualberta.ca',
    subRole: 'current',
    cohort: 'Fall 2026',
    photoInitials: 'PN',
    status: 'active',
    courses: [
      { code: 'MM 801', title: 'HCI and Applications', term: 1, status: 'completed', grade: 'A' },
      { code: 'MM 802', title: 'Multimedia Communications', term: 1, status: 'completed', grade: 'A-' },
      { code: 'MM 803', title: 'Image and Video Processing', term: 1, status: 'completed', grade: 'B+' },
      { code: 'MM 804', title: 'Graphics and Animation', term: 2, status: 'in-progress' },
      { code: 'MM 805', title: 'Computer Vision and 3DTV', term: 2, status: 'in-progress' },
      { code: 'MM 811', title: 'AI in Multimedia', term: 2, status: 'in-progress' },
    ],
    idpCompleted: true,
    ethicsHoursCompleted: 8,
    coopPermitRequired: false,
    coopPermitStatus: 'n/a',
    internship: {
      searchStatus: 'looking',
      approvalStatus: 'not-submitted',
      mm807Status: 'not-enrolled',
      mm808Status: 'not-enrolled',
      fourMonthReport: 'not-due',
      eightMonthReport: 'not-due',
      supplementaryCourses: [
        { code: 'MM 809', required: false, status: 'not-due' },
        { code: 'MM 810', required: false, status: 'not-due' },
      ],
      applications: [
        { id: 'app-1', company: 'Northlight Studios', role: 'Multimedia Software Intern', appliedOn: '2027-01-14', status: 'applied' },
        { id: 'app-2', company: 'Aurora Health Analytics', role: 'Computer Vision Intern', appliedOn: '2027-01-20', status: 'interviewing' },
      ],
    },
    graduationChecklist: defaultGradChecklist(),
    forms: defaultForms({ 'idp-workbook': 'submitted', 'ethics-records': 'submitted' }),
    needsAttention: undefined,
    linkedinSetupStep: 3,
  },
  {
    id: 'stu-002',
    name: 'Marcus Ferreira',
    ccid: 'mferreir',
    email: 'mferreir@ualberta.ca',
    subRole: 'current',
    cohort: 'Fall 2026',
    photoInitials: 'MF',
    status: 'active',
    courses: [
      { code: 'MM 801', title: 'HCI and Applications', term: 1, status: 'completed', grade: 'B' },
      { code: 'MM 802', title: 'Multimedia Communications', term: 1, status: 'completed', grade: 'B+' },
      { code: 'MM 803', title: 'Image and Video Processing', term: 1, status: 'completed', grade: 'B' },
      { code: 'MM 804', title: 'Graphics and Animation', term: 2, status: 'in-progress' },
      { code: 'MM 805', title: 'Computer Vision and 3DTV', term: 2, status: 'in-progress' },
      { code: 'MM 811', title: 'AI in Multimedia', term: 2, status: 'in-progress' },
    ],
    idpCompleted: false,
    ethicsHoursCompleted: 4,
    coopPermitRequired: true,
    coopPermitStatus: 'not-started',
    internship: {
      searchStatus: 'not-started',
      approvalStatus: 'not-submitted',
      mm807Status: 'not-enrolled',
      mm808Status: 'not-enrolled',
      fourMonthReport: 'not-due',
      eightMonthReport: 'not-due',
      supplementaryCourses: [
        { code: 'MM 809', required: false, status: 'not-due' },
        { code: 'MM 810', required: false, status: 'not-due' },
      ],
      applications: [],
    },
    graduationChecklist: defaultGradChecklist(),
    forms: defaultForms({ 'idp-workbook': 'in-progress' }),
    needsAttention: 'Ethics training incomplete (4/8 hrs) and internship search not started',
    linkedinSetupStep: 0,
  },
  {
    id: 'stu-003',
    name: 'Yuki Tanaka',
    ccid: 'ytanaka',
    email: 'ytanaka@ualberta.ca',
    subRole: 'current',
    cohort: 'Fall 2026',
    photoInitials: 'YT',
    status: 'active',
    courses: [
      { code: 'MM 801', title: 'HCI and Applications', term: 1, status: 'completed', grade: 'A' },
      { code: 'MM 802', title: 'Multimedia Communications', term: 1, status: 'completed', grade: 'A' },
      { code: 'MM 803', title: 'Image and Video Processing', term: 1, status: 'completed', grade: 'A-' },
      { code: 'MM 804', title: 'Graphics and Animation', term: 2, status: 'in-progress' },
      { code: 'MM 805', title: 'Computer Vision and 3DTV', term: 2, status: 'in-progress' },
      { code: 'MM 811', title: 'AI in Multimedia', term: 2, status: 'in-progress' },
    ],
    idpCompleted: true,
    ethicsHoursCompleted: 8,
    coopPermitRequired: false,
    coopPermitStatus: 'n/a',
    internship: {
      searchStatus: 'offer',
      companyOrGroup: 'Beacon Interactive Inc.',
      project: 'Real-time video compression for live streaming',
      approvalStatus: 'pending',
      mm807Status: 'not-enrolled',
      mm808Status: 'not-enrolled',
      fourMonthReport: 'not-due',
      eightMonthReport: 'not-due',
      supplementaryCourses: [
        { code: 'MM 809', required: false, status: 'not-due' },
        { code: 'MM 810', required: false, status: 'not-due' },
      ],
      applications: [
        { id: 'app-1', company: 'Beacon Interactive Inc.', role: 'Video Systems Intern', appliedOn: '2027-01-05', status: 'offer' },
      ],
    },
    graduationChecklist: defaultGradChecklist(),
    forms: defaultForms({ 'idp-workbook': 'submitted', 'ethics-records': 'submitted', 'internship-approval': 'in-progress' }),
    linkedinSetupStep: 5,
  },
  {
    id: 'stu-004',
    name: 'Chidi Okafor',
    ccid: 'cokafor',
    email: 'cokafor@ualberta.ca',
    subRole: 'current',
    cohort: 'Fall 2025',
    photoInitials: 'CO',
    status: 'on-internship',
    courses: [
      { code: 'MM 801', title: 'HCI and Applications', term: 1, status: 'completed', grade: 'A-' },
      { code: 'MM 802', title: 'Multimedia Communications', term: 1, status: 'completed', grade: 'B+' },
      { code: 'MM 806', title: 'Virtual Reality and Tele-Presence', term: 1, status: 'completed', grade: 'A' },
      { code: 'MM 804', title: 'Graphics and Animation', term: 2, status: 'completed', grade: 'A-' },
      { code: 'MM 805', title: 'Computer Vision and 3DTV', term: 2, status: 'completed', grade: 'B+' },
      { code: 'MM 812', title: 'Multimedia Topic', term: 2, status: 'completed', grade: 'A' },
    ],
    idpCompleted: true,
    ethicsHoursCompleted: 8,
    coopPermitRequired: true,
    coopPermitStatus: 'complete',
    internship: {
      searchStatus: 'active',
      companyOrGroup: 'Glacier Immersive Labs',
      project: 'VR training simulation for industrial safety',
      durationMonths: 8,
      startMonth: '2026-09',
      endMonth: '2027-04',
      approvalStatus: 'approved',
      mm807Status: 'enrolled',
      mm808Status: 'enrolled',
      fourMonthReport: 'submitted',
      eightMonthReport: 'due',
      supplementaryCourses: [
        { code: 'MM 809', required: false, status: 'not-due' },
        { code: 'MM 810', required: false, status: 'not-due' },
      ],
      applications: [
        { id: 'app-1', company: 'Glacier Immersive Labs', role: 'VR Software Intern', appliedOn: '2026-06-01', status: 'offer' },
      ],
    },
    graduationChecklist: defaultGradChecklist({ courses: true }),
    forms: defaultForms({
      'idp-workbook': 'submitted',
      'ethics-records': 'submitted',
      'coop-permit': 'approved' as FormRecord['status'],
      'internship-approval': 'approved',
    }),
    linkedinSetupStep: 5,
  },
  {
    id: 'stu-005',
    name: 'Sofia Mendes',
    ccid: 'smendes',
    email: 'smendes@ualberta.ca',
    subRole: 'current',
    cohort: 'Fall 2025',
    photoInitials: 'SM',
    status: 'on-internship',
    courses: [
      { code: 'MM 801', title: 'HCI and Applications', term: 1, status: 'completed', grade: 'B+' },
      { code: 'MM 803', title: 'Image and Video Processing', term: 1, status: 'completed', grade: 'A' },
      { code: 'MM 806', title: 'Virtual Reality and Tele-Presence', term: 1, status: 'completed', grade: 'A-' },
      { code: 'MM 804', title: 'Graphics and Animation', term: 2, status: 'completed', grade: 'B+' },
      { code: 'MM 811', title: 'AI in Multimedia', term: 2, status: 'completed', grade: 'A' },
      { code: 'MM 812', title: 'Multimedia Topic', term: 2, status: 'completed', grade: 'A-' },
    ],
    idpCompleted: true,
    ethicsHoursCompleted: 8,
    coopPermitRequired: false,
    coopPermitStatus: 'n/a',
    internship: {
      searchStatus: 'active',
      companyOrGroup: 'Dr. Elaine Wu Research Group (MRC)',
      project: 'Multimodal sentiment analysis for accessibility tools',
      durationMonths: 8,
      startMonth: '2026-08',
      endMonth: '2027-03',
      approvalStatus: 'approved',
      mm807Status: 'enrolled',
      mm808Status: 'enrolled',
      fourMonthReport: 'approved',
      eightMonthReport: 'due',
      supplementaryCourses: [
        { code: 'MM 809', required: true, status: 'submitted' },
        { code: 'MM 810', required: false, status: 'not-due' },
      ],
      applications: [],
    },
    graduationChecklist: defaultGradChecklist({ courses: true }),
    forms: defaultForms({
      'idp-workbook': 'submitted',
      'ethics-records': 'submitted',
      'internship-approval': 'approved',
    }),
    linkedinSetupStep: 5,
  },
  {
    id: 'stu-006',
    name: 'Ben Whitehorse',
    ccid: 'bwhiteho',
    email: 'bwhiteho@ualberta.ca',
    subRole: 'current',
    cohort: 'Fall 2026',
    photoInitials: 'BW',
    status: 'active',
    courses: [
      { code: 'MM 801', title: 'HCI and Applications', term: 1, status: 'in-progress' },
      { code: 'MM 802', title: 'Multimedia Communications', term: 1, status: 'in-progress' },
      { code: 'MM 803', title: 'Image and Video Processing', term: 1, status: 'in-progress' },
      { code: 'MM 804', title: 'Graphics and Animation', term: 2, status: 'upcoming' },
      { code: 'MM 805', title: 'Computer Vision and 3DTV', term: 2, status: 'upcoming' },
      { code: 'MM 811', title: 'AI in Multimedia', term: 2, status: 'upcoming' },
    ],
    idpCompleted: false,
    ethicsHoursCompleted: 2,
    coopPermitRequired: false,
    coopPermitStatus: 'n/a',
    internship: {
      searchStatus: 'not-started',
      approvalStatus: 'not-submitted',
      mm807Status: 'not-enrolled',
      mm808Status: 'not-enrolled',
      fourMonthReport: 'not-due',
      eightMonthReport: 'not-due',
      supplementaryCourses: [
        { code: 'MM 809', required: false, status: 'not-due' },
        { code: 'MM 810', required: false, status: 'not-due' },
      ],
      applications: [],
    },
    graduationChecklist: defaultGradChecklist(),
    forms: defaultForms(),
    linkedinSetupStep: 1,
  },
  {
    id: 'stu-007',
    name: 'Grace Kim',
    ccid: 'gkim2',
    email: 'gkim2@ualberta.ca',
    subRole: 'alumni',
    cohort: 'Fall 2024',
    photoInitials: 'GK',
    status: 'graduated',
    courses: [
      { code: 'MM 801', title: 'HCI and Applications', term: 1, status: 'completed', grade: 'A' },
      { code: 'MM 802', title: 'Multimedia Communications', term: 1, status: 'completed', grade: 'A' },
      { code: 'MM 803', title: 'Image and Video Processing', term: 1, status: 'completed', grade: 'A-' },
      { code: 'MM 804', title: 'Graphics and Animation', term: 2, status: 'completed', grade: 'A' },
      { code: 'MM 805', title: 'Computer Vision and 3DTV', term: 2, status: 'completed', grade: 'A-' },
      { code: 'MM 811', title: 'AI in Multimedia', term: 2, status: 'completed', grade: 'A' },
    ],
    idpCompleted: true,
    ethicsHoursCompleted: 8,
    coopPermitRequired: false,
    coopPermitStatus: 'n/a',
    internship: {
      searchStatus: 'completed',
      companyOrGroup: 'Fenwick Media Systems',
      project: 'Automated highlight generation for sports broadcast',
      durationMonths: 8,
      startMonth: '2025-05',
      endMonth: '2025-12',
      approvalStatus: 'approved',
      mm807Status: 'completed',
      mm808Status: 'completed',
      fourMonthReport: 'approved',
      eightMonthReport: 'approved',
      supplementaryCourses: [
        { code: 'MM 809', required: false, status: 'not-due' },
        { code: 'MM 810', required: false, status: 'not-due' },
      ],
      applications: [],
    },
    graduationChecklist: defaultGradChecklist({
      'idp-pd': true,
      courses: true,
      'internship-credits': true,
      'bear-tracks': true,
      'final-grade': true,
      'completion-letter': true,
    }),
    forms: defaultForms({
      'idp-workbook': 'approved',
      'ethics-records': 'approved',
      'internship-approval': 'approved',
      'idp-pd-completion': 'approved',
    }),
    linkedinSetupStep: 5,
    gradYear: '2026',
    currentRole: 'Media Systems Engineer',
    currentCompany: 'Fenwick Media Systems',
  },
  {
    id: 'stu-008',
    name: 'Ahmed Siddiqui',
    ccid: 'asiddiq',
    email: 'asiddiq@ualberta.ca',
    subRole: 'current',
    cohort: 'Fall 2026',
    photoInitials: 'AS',
    status: 'active',
    courses: [
      { code: 'MM 801', title: 'HCI and Applications', term: 1, status: 'completed', grade: 'B' },
      { code: 'MM 802', title: 'Multimedia Communications', term: 1, status: 'completed', grade: 'B-' },
      { code: 'MM 803', title: 'Image and Video Processing', term: 1, status: 'completed', grade: 'C+' },
      { code: 'MM 804', title: 'Graphics and Animation', term: 2, status: 'in-progress' },
      { code: 'MM 805', title: 'Computer Vision and 3DTV', term: 2, status: 'in-progress' },
      { code: 'MM 811', title: 'AI in Multimedia', term: 2, status: 'in-progress' },
    ],
    idpCompleted: true,
    ethicsHoursCompleted: 6,
    coopPermitRequired: true,
    coopPermitStatus: 'in-progress',
    internship: {
      searchStatus: 'interviewing',
      approvalStatus: 'not-submitted',
      mm807Status: 'not-enrolled',
      mm808Status: 'not-enrolled',
      fourMonthReport: 'not-due',
      eightMonthReport: 'not-due',
      supplementaryCourses: [
        { code: 'MM 809', required: false, status: 'not-due' },
        { code: 'MM 810', required: false, status: 'not-due' },
      ],
      applications: [
        { id: 'app-1', company: 'Tundra Games', role: 'Gameplay Systems Intern', appliedOn: '2027-01-10', status: 'interviewing' },
        { id: 'app-2', company: 'ClearFrame Media', role: 'Video Pipeline Intern', appliedOn: '2027-01-18', status: 'rejected' },
      ],
    },
    graduationChecklist: defaultGradChecklist(),
    forms: defaultForms({ 'idp-workbook': 'submitted', 'coop-permit': 'in-progress' }),
    needsAttention: 'Co-op permit in progress with an internship interview already underway — confirm timing',
    linkedinSetupStep: 4,
  },
]

export function getStudentById(id: string): Student | undefined {
  return STUDENTS.find((s) => s.id === id)
}

export function getCurrentStudents(): Student[] {
  return STUDENTS.filter((s) => s.subRole === 'current')
}

export function getAlumni(): Student[] {
  return STUDENTS.filter((s) => s.subRole === 'alumni')
}
